# Generated by Django 4.2.5 on 2023-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], max_length=50)),
                ('product_image', models.ImageField(upload_to='products_images')),
            ],
        ),
    ]
